name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  register-example:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: unionai/flytectl-setup-action@master
      - name: Create Flyte sandbox cluster
        run: | 
           flytectl sandbox start
           flytectl config init
      - uses: ./ # Run the local version of the action.
        with:
          flytesnacks: true
          project: flytesnacks
          version: v0.1.1
          domain: development